name = "BINF301-code"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataSets = "c9661210-8a83-48f0-b833-72e62abce419"
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FreqTables = "da1fdf0e-e0ff-5433-a45f-9bb5ff651cb1"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GLMNet = "8d5ece8b-de18-5317-b113-243142960cc6"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
JuliaHub = "bc7fa6ce-b75e-4d60-89ad-56c957190b6e"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJLIBSVMInterface = "61c7150f-6c77-4bb1-949c-13197eac2a52"
MLJLinearModels = "6ee0df7b-362f-4a72-a706-9e79364fb692"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MLJModels = "d491faf4-2d78-11e9-2867-c94bc002c0b7"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SingleCellProjections = "03d38035-ed2f-4a36-82eb-797f1727ab2e"
SmoothingSplines = "102930c3-cf33-599f-b3b1-9a29a5acab30"
SpatialOmicsGPs = "e145bb07-96d9-421f-b0a2-c579a69b21bf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TSne = "24678dba-d5e9-5843-a4c6-250288b04835"
UMAP = "c4f8c510-2410-5be4-91d7-4fbaeb39457e"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
DrWatson = "2.13.0"
julia = "1.10.0"
